backend:
  image:
    repository: ealen/echo-server
    tag: latest
  service:
    port: 80

frontend:
  image:
    repository: nginx
    tag: latest
  service:
    port: 80

postgres:
  image:
    repository: bitnami/postgresql
    tag: "17.5.0"
  auth:
    username: user
    password: pass
    database: base
