apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: '{{ printf "%s:%s" .Values.postgres.image.repository .Values.postgres.image.tag }}'
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.auth.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.auth.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.auth.password }}"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
